# Generated by Django 3.2.6 on 2021-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registerday',
            new_name='Uregisterday',
        ),
        migrations.AlterField(
            model_name='user',
            name='Ucombid',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='사업자등록번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Utel',
            field=models.CharField(max_length=15, verbose_name='휴대전화번호'),
        ),
    ]
