# Generated by Django 3.2.6 on 2021-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210915_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Upostcode',
            field=models.CharField(max_length=7, verbose_name='우편번호'),
        ),
    ]
