# Generated by Django 3.2.6 on 2021-09-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_upostcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Ucombrith',
            field=models.DateField(null=True, verbose_name='회사설립일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ucomdepart',
            field=models.CharField(choices=[('1', '제조'), ('2', 'IT'), ('3', '도소매'), ('4', '서비스'), ('5', '사회적기업')], max_length=1, null=True, verbose_name='창업분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ucomname',
            field=models.CharField(max_length=15, null=True, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ucomsector',
            field=models.CharField(max_length=20, null=True, verbose_name='업종'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ucomstyle',
            field=models.CharField(max_length=20, null=True, verbose_name='업태'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ucomtype',
            field=models.CharField(choices=[('1', '개인사업자'), ('2', '(주)주식회사'), ('3', '주식회사(주)'), ('4', '유한회사'), ('5', '사단법인'), ('6', '재단법인'), ('7', '학교'), ('8', '공공기관'), ('9', '기타')], max_length=1, null=True, verbose_name='회사유형'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ufounderbrith',
            field=models.DateField(null=True, verbose_name='창업자 생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ufoundergender',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(woman)')], max_length=1, null=True, verbose_name='창업자 성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ufoundername',
            field=models.CharField(max_length=12, null=True, verbose_name='대표자명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ufoundyear',
            field=models.CharField(choices=[('1', '예비창업자'), ('2', '창업초기(3년 미만)'), ('3', '창업도약(4년 ~ 7년)'), ('4', '7년 이상')], max_length=1, null=True, verbose_name='창업업력'),
        ),
    ]
