# Generated by Django 3.2.6 on 2021-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210916_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Ucombrith',
            field=models.DateField(blank=True, null=True, verbose_name='회사설립일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ufounderbrith',
            field=models.DateField(blank=True, null=True, verbose_name='창업자 생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Ufoundergender',
            field=models.CharField(blank=True, choices=[('M', '남성(Man)'), ('W', '여성(woman)')], max_length=1, null=True, verbose_name='창업자 성별'),
        ),
    ]
