# Generated by Django 3.2.6 on 2021-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='Mberterm',
            field=models.TextField(max_length=12000, verbose_name='회원가입약관'),
        ),
        migrations.AlterField(
            model_name='term',
            name='Privterm',
            field=models.TextField(max_length=12000, verbose_name='개인정보처리방침'),
        ),
    ]
