# Generated by Django 3.2.6 on 2021-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20210918_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exituser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=10000, verbose_name='탈퇴사유')),
                ('Utype', models.CharField(choices=[('normal', '일반회원'), ('company', '기업회원')], max_length=7, verbose_name='회원유형')),
                ('UID', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('UPW', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('Unick', models.CharField(max_length=20, verbose_name='닉네임')),
                ('Uname', models.CharField(max_length=12, verbose_name='이름')),
                ('Ubrith', models.DateField(verbose_name='생년월일')),
                ('Ugender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(woman)')], max_length=1, verbose_name='성별')),
                ('Unation', models.CharField(choices=[('KR', '대한민국'), ('ETC', '국외')], max_length=3, verbose_name='국가')),
                ('Utel', models.CharField(max_length=15, verbose_name='휴대전화번호')),
                ('Uemail', models.EmailField(max_length=60, verbose_name='이메일')),
                ('Upostcode', models.CharField(max_length=7, verbose_name='우편번호')),
                ('Uaddress', models.CharField(max_length=200, verbose_name='주소')),
                ('Usmsrecive', models.BooleanField(default=False, verbose_name='SMS동의여부')),
                ('Umailrecive', models.BooleanField(default=False, verbose_name='이메일수신동의여부')),
                ('Ucomtype', models.CharField(choices=[('1', '개인사업자'), ('2', '(주)주식회사'), ('3', '주식회사(주)'), ('4', '유한회사'), ('5', '사단법인'), ('6', '재단법인'), ('7', '학교'), ('8', '공공기관'), ('9', '기타')], max_length=1, null=True, verbose_name='회사유형')),
                ('Ucomname', models.CharField(max_length=15, null=True, verbose_name='회사명')),
                ('Ucombid', models.CharField(max_length=12, null=True, unique=True, verbose_name='사업자등록번호')),
                ('Ufoundername', models.CharField(max_length=12, null=True, verbose_name='대표자명')),
                ('Ucomstyle', models.CharField(max_length=20, null=True, verbose_name='업태')),
                ('Ucomsector', models.CharField(max_length=20, null=True, verbose_name='업종')),
                ('Ucombrith', models.DateField(blank=True, null=True, verbose_name='회사설립일')),
                ('Ufounderbrith', models.DateField(blank=True, null=True, verbose_name='창업자 생년월일')),
                ('Ufoundergender', models.CharField(blank=True, choices=[('M', '남성(Man)'), ('W', '여성(woman)')], max_length=1, null=True, verbose_name='창업자 성별')),
                ('Ufoundyear', models.CharField(choices=[('1', '예비창업자'), ('2', '창업초기(3년 미만)'), ('3', '창업도약(4년 ~ 7년)'), ('4', '7년 이상')], max_length=1, null=True, verbose_name='창업업력')),
                ('Ucomdepart', models.CharField(choices=[('1', '제조'), ('2', 'IT'), ('3', '도소매'), ('4', '서비스'), ('5', '사회적기업')], max_length=1, null=True, verbose_name='창업분야')),
                ('Uregisterday', models.DateTimeField(verbose_name='등록일')),
            ],
        ),
    ]
