# Generated by Django 3.2.6 on 2021-09-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20210924_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_categ_sma',
            name='Big',
        ),
    ]
