# Generated by Django 3.2.6 on 2021-09-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20210927_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.prod_categ_mid', verbose_name='중분류선택'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.prod_categ_sma', verbose_name='소분류선택'),
        ),
    ]
