# Generated by Django 3.2.6 on 2021-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_alter_product_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devlivery_term',
            options={'verbose_name': '배송정책', 'verbose_name_plural': '배송정책'},
        ),
        migrations.AlterModelOptions(
            name='exituser',
            options={'verbose_name': '탈퇴회원', 'verbose_name_plural': '탈퇴회원'},
        ),
        migrations.AlterModelOptions(
            name='prod_categ_big',
            options={'verbose_name': '대분류', 'verbose_name_plural': '대분류'},
        ),
        migrations.AlterModelOptions(
            name='prod_categ_mid',
            options={'verbose_name': '중분류', 'verbose_name_plural': '중분류'},
        ),
        migrations.AlterModelOptions(
            name='prod_categ_sma',
            options={'verbose_name': '소분류', 'verbose_name_plural': '소분류'},
        ),
        migrations.AlterModelOptions(
            name='product_qna',
            options={'verbose_name': '상품문의', 'verbose_name_plural': '상품문의'},
        ),
        migrations.AlterModelOptions(
            name='product_review',
            options={'verbose_name': '상품후기', 'verbose_name_plural': '상품후기'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': '약관', 'verbose_name_plural': '약관'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원'},
        ),
        migrations.AlterField(
            model_name='prod_categ_big',
            name='Code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='대분류코드'),
        ),
        migrations.AlterField(
            model_name='prod_categ_mid',
            name='Code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='중분류코드'),
        ),
        migrations.AlterField(
            model_name='prod_categ_sma',
            name='Code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='소분류코드'),
        ),
    ]
