# Generated by Django 3.2.6 on 2021-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20210928_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_reviewimg',
            options={'verbose_name': '이미지업로드', 'verbose_name_plural': '이미지업로드'},
        ),
        migrations.AlterModelOptions(
            name='product_thumb',
            options={'verbose_name': '이미지업로드', 'verbose_name_plural': '이미지업로드'},
        ),
        migrations.AlterField(
            model_name='product',
            name='Code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='상품분류코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='상품명'),
        ),
    ]
