# Generated by Django 3.2.6 on 2021-09-28 12:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('member', '0015_auto_20210928_2154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devlivery_com',
            table='ideafarm_Delicom',
        ),
    ]
