# Generated by Django 3.2.6 on 2021-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='EndPrice',
            field=models.PositiveIntegerField(default=0, verbose_name='판매가(원)'),
        ),
    ]
