# Generated by Django 3.2.6 on 2021-10-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_product_endprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SimExplanation',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='상품간단설명'),
        ),
    ]
