# Generated by Django 3.2.6 on 2021-10-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20211004_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='Asker',
            new_name='Reviewer',
        ),
        migrations.AddField(
            model_name='product_review',
            name='ReTitle',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='Content',
            field=models.TextField(db_index=True, max_length=10000, verbose_name='내용'),
        ),
    ]
